# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://prices.algotest.xyz/:splat"
  status = 200
  force = true
  headers = { X-Forwarded-Host = "your-site.netlify.app" }
